name: publish
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
permissions:
  contents: write
  id-token: write
"on":
  workflow_dispatch:
    inputs:
      run_id:
        description: "Run ID to download artifacts from"
        required: true
      ziyy:
        description: "Publish ziyy package"
        type: boolean
        required: true
      ziyy-core:
        description: "Publish ziyy-core package"
        type: boolean
        required: true
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          run-id: ${{ inputs.run_id }}
          github-token: ${{ secrets.GH_PAT }}
          repository: ziyy-dev/ziyy-js
      - name: Move artifacts
        run: yarn artifacts
      - name: List packages
        run: ls -R ./npm
        shell: bash
      - name: Set up NPM
        run: |
          yarn config set npmAuthToken $NPM_TOKEN
          yarn config set npmPublishProvenance true
          yarn config set npmPublishAccess public
      - name: Publish ziyy
        if: ${{ inputs.ziyy }}
        run: |
          cd packages/ziyy
          yarn build
          yarn npm publish --tolerate-republish
      - name: Publish @ziyy/core
        if: ${{ inputs.ziyy-core }}
        run: |
          yarn mgr publish
          yarn npm publish --tolerate-republish
